### ISSUE TITLE
Copy Verse No Longer Works?

### ISSUE THREAD

**Issue by BPontevorvo** [caleb531/youversion-suggest-alfred#13]
Hey there!

Seems like there is an error when I try to type a verse or range of verses and try to copy them to the clipboard! Any help would be appreciated.

**Comment by caleb531** [comment]
@BPontevorvo What specific verse / verse range are you trying to copy?

**Comment by BPontevorvo** [comment]
@caleb531 I was trying to copy Psalm 16. But it is actually an issue with any reference I try and copy. Sometimes, when I am using command enter to copy nothing at all happens, and the Alfred pop up just stays on the screen, other times, it closes and the information is not copied. I am still able to use it to navigate to the website though.

**Comment by caleb531** [comment]
@BPontevorvo Can you open the Debugger (looks like a bug icon) in the workflow area? If you run the workflow again, any errors should appear here.

![Uploading Screen Shot 2020-10-14 at 8.37.23 AM.png…]()

**Comment by BPontevorvo** [comment]
Absolutely. Here is what shows up. Thanks for being so responsive!
<img width="1103" alt="Screen Shot 2020-10-14 at 11 41 11 AM" src="https://user-images.githubusercontent.com/72838123/96012561-39643200-0e12-11eb-9c88-93a21b36f8d1.png">

**Comment by BPontevorvo** [comment]
@caleb531 Here is the full text if that is helpful.

[11:39:36.260] Logging Stopped.
[11:39:37.688] Logging Started...
[11:39:43.294] YouVersion Suggest[Script Filter] Queuing argument 'J'
[11:39:43.411] YouVersion Suggest[Script Filter] Script with argv 'J' finished
[11:39:43.414] YouVersion Suggest[Script Filter] {"items": [{"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Joshua 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jos.1", "title": "Joshua 1 (NIV)", "text": {"copy": "Joshua 1 (NIV)", "largetype": "Joshua 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JOS.1", "copybydefault": "True"}, "arg": "111/jos.1", "quicklookurl": "https://www.bible.com/bible/111/JOS.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Judges 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jdg.1", "title": "Judges 1 (NIV)", "text": {"copy": "Judges 1 (NIV)", "largetype": "Judges 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JDG.1", "copybydefault": "True"}, "arg": "111/jdg.1", "quicklookurl": "https://www.bible.com/bible/111/JDG.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Job 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/job.1", "title": "Job 1 (NIV)", "text": {"copy": "Job 1 (NIV)", "largetype": "Job 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JOB.1", "copybydefault": "True"}, "arg": "111/job.1", "quicklookurl": "https://www.bible.com/bible/111/JOB.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Jeremiah 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jer.1", "title": "Jeremiah 1 (NIV)", "text": {"copy": "Jeremiah 1 (NIV)", "largetype": "Jeremiah 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JER.1", "copybydefault": "True"}, "arg": "111/jer.1", "quicklookurl": "https://www.bible.com/bible/111/JER.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Joel 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jol.1", "title": "Joel 1 (NIV)", "text": {"copy": "Joel 1 (NIV)", "largetype": "Joel 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JOL.1", "copybydefault": "True"}, "arg": "111/jol.1", "quicklookurl": "https://www.bible.com/bible/111/JOL.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Jonah 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jon.1", "title": "Jonah 1 (NIV)", "text": {"copy": "Jonah 1 (NIV)", "largetype": "Jonah 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JON.1", "copybydefault": "True"}, "arg": "111/jon.1", "quicklookurl": "https://www.bible.com/bible/111/JON.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jhn.1", "title": "John 1 (NIV)", "text": {"copy": "John 1 (NIV)", "largetype": "John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JHN.1", "copybydefault": "True"}, "arg": "111/jhn.1", "quicklookurl": "https://www.bible.com/bible/111/JHN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "James 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jas.1", "title": "James 1 (NIV)", "text": {"copy": "James 1 (NIV)", "largetype": "James 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JAS.1", "copybydefault": "True"}, "arg": "111/jas.1", "quicklookurl": "https://www.bible.com/bible/111/JAS.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Jude 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jud.1", "title": "Jude 1 (NIV)", "text": {"copy": "Jude 1 (NIV)", "largetype": "Jude 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JUD.1", "copybydefault": "True"}, "arg": "111/jud.1", "quicklookurl": "https://www.bible.com/bible/111/JUD.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "1 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/1jn.1", "title": "1 John 1 (NIV)", "text": {"copy": "1 John 1 (NIV)", "largetype": "1 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/1JN.1", "copybydefault": "True"}, "arg": "111/1jn.1", "quicklookurl": "https://www.bible.com/bible/111/1JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "2 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/2jn.1", "title": "2 John 1 (NIV)", "text": {"copy": "2 John 1 (NIV)", "largetype": "2 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/2JN.1", "copybydefault": "True"}, "arg": "111/2jn.1", "quicklookurl": "https://www.bible.com/bible/111/2JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "3 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/3jn.1", "title": "3 John 1 (NIV)", "text": {"copy": "3 John 1 (NIV)", "largetype": "3 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/3JN.1", "copybydefault": "True"}, "arg": "111/3jn.1", "quicklookurl": "https://www.bible.com/bible/111/3JN.1", "icon": {"path": "icon.png"}}]}
[11:39:43.445] YouVersion Suggest[Script Filter] Queuing argument 'Jo'
[11:39:43.551] YouVersion Suggest[Script Filter] Script with argv 'Jo' finished
[11:39:43.560] YouVersion Suggest[Script Filter] {"items": [{"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Joshua 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jos.1", "title": "Joshua 1 (NIV)", "text": {"copy": "Joshua 1 (NIV)", "largetype": "Joshua 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JOS.1", "copybydefault": "True"}, "arg": "111/jos.1", "quicklookurl": "https://www.bible.com/bible/111/JOS.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Job 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/job.1", "title": "Job 1 (NIV)", "text": {"copy": "Job 1 (NIV)", "largetype": "Job 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JOB.1", "copybydefault": "True"}, "arg": "111/job.1", "quicklookurl": "https://www.bible.com/bible/111/JOB.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Joel 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jol.1", "title": "Joel 1 (NIV)", "text": {"copy": "Joel 1 (NIV)", "largetype": "Joel 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JOL.1", "copybydefault": "True"}, "arg": "111/jol.1", "quicklookurl": "https://www.bible.com/bible/111/JOL.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "Jonah 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jon.1", "title": "Jonah 1 (NIV)", "text": {"copy": "Jonah 1 (NIV)", "largetype": "Jonah 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JON.1", "copybydefault": "True"}, "arg": "111/jon.1", "quicklookurl": "https://www.bible.com/bible/111/JON.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jhn.1", "title": "John 1 (NIV)", "text": {"copy": "John 1 (NIV)", "largetype": "John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JHN.1", "copybydefault": "True"}, "arg": "111/jhn.1", "quicklookurl": "https://www.bible.com/bible/111/JHN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "1 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/1jn.1", "title": "1 John 1 (NIV)", "text": {"copy": "1 John 1 (NIV)", "largetype": "1 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/1JN.1", "copybydefault": "True"}, "arg": "111/1jn.1", "quicklookurl": "https://www.bible.com/bible/111/1JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "2 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/2jn.1", "title": "2 John 1 (NIV)", "text": {"copy": "2 John 1 (NIV)", "largetype": "2 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/2JN.1", "copybydefault": "True"}, "arg": "111/2jn.1", "quicklookurl": "https://www.bible.com/bible/111/2JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "3 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/3jn.1", "title": "3 John 1 (NIV)", "text": {"copy": "3 John 1 (NIV)", "largetype": "3 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/3JN.1", "copybydefault": "True"}, "arg": "111/3jn.1", "quicklookurl": "https://www.bible.com/bible/111/3JN.1", "icon": {"path": "icon.png"}}]}
[11:39:43.590] YouVersion Suggest[Script Filter] Queuing argument 'Joh'
[11:39:43.695] YouVersion Suggest[Script Filter] Script with argv 'Joh' finished
[11:39:43.706] YouVersion Suggest[Script Filter] {"items": [{"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jhn.1", "title": "John 1 (NIV)", "text": {"copy": "John 1 (NIV)", "largetype": "John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JHN.1", "copybydefault": "True"}, "arg": "111/jhn.1", "quicklookurl": "https://www.bible.com/bible/111/JHN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "1 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/1jn.1", "title": "1 John 1 (NIV)", "text": {"copy": "1 John 1 (NIV)", "largetype": "1 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/1JN.1", "copybydefault": "True"}, "arg": "111/1jn.1", "quicklookurl": "https://www.bible.com/bible/111/1JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "2 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/2jn.1", "title": "2 John 1 (NIV)", "text": {"copy": "2 John 1 (NIV)", "largetype": "2 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/2JN.1", "copybydefault": "True"}, "arg": "111/2jn.1", "quicklookurl": "https://www.bible.com/bible/111/2JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "3 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/3jn.1", "title": "3 John 1 (NIV)", "text": {"copy": "3 John 1 (NIV)", "largetype": "3 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/3JN.1", "copybydefault": "True"}, "arg": "111/3jn.1", "quicklookurl": "https://www.bible.com/bible/111/3JN.1", "icon": {"path": "icon.png"}}]}
[11:39:43.758] YouVersion Suggest[Script Filter] Queuing argument 'John'
[11:39:43.863] YouVersion Suggest[Script Filter] Script with argv 'John' finished
[11:39:43.870] YouVersion Suggest[Script Filter] {"items": [{"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/jhn.1", "title": "John 1 (NIV)", "text": {"copy": "John 1 (NIV)", "largetype": "John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/JHN.1", "copybydefault": "True"}, "arg": "111/jhn.1", "quicklookurl": "https://www.bible.com/bible/111/JHN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "1 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/1jn.1", "title": "1 John 1 (NIV)", "text": {"copy": "1 John 1 (NIV)", "largetype": "1 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/1JN.1", "copybydefault": "True"}, "arg": "111/1jn.1", "quicklookurl": "https://www.bible.com/bible/111/1JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "2 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/2jn.1", "title": "2 John 1 (NIV)", "text": {"copy": "2 John 1 (NIV)", "largetype": "2 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/2JN.1", "copybydefault": "True"}, "arg": "111/2jn.1", "quicklookurl": "https://www.bible.com/bible/111/2JN.1", "icon": {"path": "icon.png"}}, {"mods": {"cmd": {"subtitle": "View on YouVersion"}, "ctrl": {"arg": "3 John 1 (NIV)"}}, "subtitle": "Copy content to clipboard", "uid": "yvs-111/3jn.1", "title": "3 John 1 (NIV)", "text": {"copy": "3 John 1 (NIV)", "largetype": "3 John 1 (NIV)"}, "variables": {"ref_url": "https://www.bible.com/bible/111/3JN.1", "copybydefault": "True"}, "arg": "111/3jn.1", "quicklookurl": "https://www.bible.com/bible/111/3JN.1", "icon": {"path": "icon.png"}}]}
[11:39:47.937] YouVersion Suggest[Script Filter] Processing complete
[11:39:47.938] YouVersion Suggest[Script Filter] Passing output '111/jhn.1' to Conditional
[11:39:47.939] YouVersion Suggest[Conditional] Processing complete
[11:39:47.940] YouVersion Suggest[Conditional] Passing output '111/jhn.1' to Run Script
[11:39:48.106] ERROR: YouVersion Suggest[Run Script] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/brettpontecorvo/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BC869A8F-44AC-4667-8DD4-043633159551/yvs/copy_ref.py", line 209, in <module>
    main(sys.argv[1].decode('utf-8'))
  File "/Users/brettpontecorvo/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BC869A8F-44AC-4667-8DD4-043633159551/yvs/copy_ref.py", line 201, in main
    'copied_ref': get_copied_ref_from_object(ref, user_prefs),
  File "/Users/brettpontecorvo/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BC869A8F-44AC-4667-8DD4-043633159551/yvs/copy_ref.py", line 182, in get_copied_ref_from_object
    include_verse_numbers=user_prefs['versenumbers'])
  File "/Users/brettpontecorvo/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BC869A8F-44AC-4667-8DD4-043633159551/yvs/copy_ref.py", line 161, in get_ref_content
    parser.feed(chapter_html)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 161, in goahead
    k = self.parse_starttag(i)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 327, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "/Users/brettpontecorvo/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BC869A8F-44AC-4667-8DD4-043633159551/yvs/copy_ref.py", line 81, in handle_starttag
    elem_class_names = elem_class.split(' ')
AttributeError: 'NoneType' object has no attribute 'split'
[11:39:48.121] YouVersion Suggest[Run Script] Processing complete
[11:39:48.122] YouVersion Suggest[Run Script] Passing output '' to Copy to Clipboard
[11:39:48.122] YouVersion Suggest[Copy to Clipboard] Processing complete
[11:39:48.123] YouVersion Suggest[Copy to Clipboard] Passing output '' to Conditional
[11:39:48.124] YouVersion Suggest[Conditional] Processing complete
[11:39:48.124] YouVersion Suggest[Conditional] Passing output '' to Post Notification

**Comment by caleb531** [comment]
@BPontevorvo I can confirm I can reproduce the issue, and will work on a fix over the next few days.

**Comment by caleb531** [comment]
@BPontevorvo The issue closed automatically because I just pushed a commit indicating the fix. Will publish the new release in just a moment...

**Comment by caleb531** [comment]
@BPontevorvo Okay, I just pushed YouVersion Suggest v11.4.1 with the fix! Please try it and let me know how it works for you

https://github.com/caleb531/youversion-suggest-alfred/releases/tag/v11.4.1

**Comment by BPontevorvo** [comment]
Hey Caleb,

It works!!!!

This is my most used Alfred workflow, and I was so sad to see it not work.
Thank you SO SO much for fixing it so quickly. Very grateful..

Best,
Brett
