### ISSUE TITLE
Duplicate workflow / dual languages doesn't work w Alfred Gallery version

### ISSUE THREAD

**Issue by kenanmike** [caleb531/youversion-suggest-alfred#26]
In the previous non-Gallery version, I was able to duplicate the workflow and use different settings on the second one to setup a 2nd language version. But since the Alfred Gallery update, I can't get a duplicated workflow to work for some reason.

Here's the error code I get:
[15:58:02.970] YouVersion Suggest - COPY[Script Filter] Queuing argument ''
[15:58:03.149] YouVersion Suggest - COPY[Script Filter] Script with argv '' finished
[15:58:03.153] ERROR: YouVersion Suggest - COPY[Script Filter] Code 1: Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/michaelbaldwin/New Alfred/Alfred.alfredpreferences/workflows/user.workflow.E056C079-805D-40F8-9149-1E60C078F90D/yvs/filter_prefs.py", line 311, in <module>
    main(sys.argv[1])
  File "/Users/michaelbaldwin/New Alfred/Alfred.alfredpreferences/workflows/user.workflow.E056C079-805D-40F8-9149-1E60C078F90D/yvs/filter_prefs.py", line 299, in main
    results = get_result_list(query_str)
  File "/Users/michaelbaldwin/New Alfred/Alfred.alfredpreferences/workflows/user.workflow.E056C079-805D-40F8-9149-1E60C078F90D/yvs/filter_prefs.py", line 265, in get_result_list
    user_prefs = core.get_user_prefs()
  File "/Users/michaelbaldwin/New Alfred/Alfred.alfredpreferences/workflows/user.workflow.E056C079-805D-40F8-9149-1E60C078F90D/yvs/core.py", line 164, in get_user_prefs
    with open(get_user_prefs_path(), 'r') as prefs_file:
  File "/Users/michaelbaldwin/New Alfred/Alfred.alfredpreferences/workflows/user.workflow.E056C079-805D-40F8-9149-1E60C078F90D/yvs/core.py", line 131, in get_user_prefs_path
    return os.path.join(LOCAL_DATA_DIR_PATH, 'preferences.json')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by caleb531** [comment]
@kenanmike When you duplicate a workflow, the **Bundle ID** field in the workflow settings gets cleared. You need to double-click your duplicate workflow and enter in something like:

```
com.kenanmike.youversionsuggest
```

The ID doesn't matter—it just needs to be unique across all your installed workflows.

<img width="597" alt="Screenshot 2023-04-30 at 10 14 51 AM" src="https://user-images.githubusercontent.com/872474/235366822-bcebdac9-c343-42d3-92e4-728687fdc1cd.png">

I will consider making the workflow functional without a bundle ID populated in the future, but I make no promises.

**Comment by kenanmike** [comment]
This works. Thanks very much!

**Comment by caleb531** [comment]
@kenanmike Sure, my pleasure! Closing this issue now that we found a simple solution.
